openapi: 3.0.1
info:
  description: SOFI Sekvensanalyseplatform
  title: SOFI
  version: 0.1.0
servers:
- url: http://localhost:8080/api/
security:
- jwt: []
tags:
- description: Operations about user
  name: user
- description: Operations for isolates
  name: analysis
paths:
  /analysis:
    get:
      description: Page through all the analysis in the system
      operationId: get_analysis
      parameters:
      - description: opaque token to supply to get the next page of isolates
        explode: true
        in: query
        name: paging_token
        required: false
        schema:
          format: byte
          nullable: true
          type: string
        style: form
      - explode: true
        in: query
        name: page_size
        required: false
        schema:
          default: 100
          type: number
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PageOfAnalysis'
          description: Page of isolates
      tags:
      - analysis
      x-openapi-router-controller: web.src.SAP.generated.controllers.analysis_controller
    post:
      description: Search all analysis by given query
      operationId: search_analysis
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AnalysisQuery'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PageOfAnalysis'
          description: Page of isolates
      tags:
      - analysis
      x-openapi-router-controller: web.src.SAP.generated.controllers.analysis_controller
      x-codegen-request-body-name: query
  /analysis-history/{isolate_id}:
    get:
      description: Get analysis history by isolate_id
      operationId: get_analysis_history
      parameters:
      - description: Id of isolate
        explode: false
        in: path
        name: isolate_id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnalysisHistory'
          description: Analysis history
      tags:
      - analysis
      x-openapi-router-controller: web.src.SAP.generated.controllers.analysis_controller
  /analysis/by_id:
    get:
      description: Get an individual analysis result by sequence_id
      operationId: get_sequence_by_id
      parameters:
      - description: sequence_id of analysis result
        explode: true
        in: query
        name: sequence_id
        required: true
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SingleAnalysisResult'
          description: Analysis
      tags:
      - analysis
      x-openapi-router-controller: web.src.SAP.generated.controllers.analysis_controller
  /analysis/changes:
    post:
      description: Submit a batch of analysis data changes
      operationId: submit_changes
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AnalysisChange'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnalysisChange'
          description: Changes accepted
      tags:
      - analysis
      x-openapi-router-controller: web.src.SAP.generated.controllers.analysis_controller
      x-codegen-request-body-name: body
  /analysis/columns:
    get:
      description: Get column metadata, scoped to authenticated user
      operationId: get_columns
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Column'
                type: array
          description: Column collection
      tags:
      - analysis
      x-openapi-router-controller: web.src.SAP.generated.controllers.analysis_controller
  /analysis/comparative/newick:
    get:
      description: Get newick tree file along with metadata for a given job id.
      operationId: get_comparative_newick_data
      parameters:
      - description: Job id that points to the comparative analysis run.
        explode: true
        in: query
        name: job_id
        required: true
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewickTreeResponse'
          description: Newick tree
      tags:
      - comparative_analysis
      x-openapi-router-controller: web.src.SAP.generated.controllers.comparative_analysis_controller
  /analysis/reload_metadata:
    post:
      description: Reload metadata for a given isolate
      operationId: reload_metadata
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MetadataReloadRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetadataReloadResponse'
          description: Reload successful
      tags:
      - analysis
      x-openapi-router-controller: web.src.SAP.generated.controllers.analysis_controller
      x-codegen-request-body-name: body
  /approvals:
    get:
      description: Retrieve list of approvals for authenticated user
      operationId: get_approvals
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Approval'
                type: array
          description: List of Approvals
      tags:
      - approval
      x-openapi-router-controller: web.src.SAP.generated.controllers.approval_controller
    post:
      description: Submit approval/rejection information
      operationId: create_approval
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApprovalRequest'
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Approval'
          description: Approval accepted
      tags:
      - approval
      x-openapi-router-controller: web.src.SAP.generated.controllers.approval_controller
      x-codegen-request-body-name: body
  /approvals/matrix:
    get:
      description: Get the entire approval matrix for all analysis
      operationId: full_approval_matrix
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApprovalMatrix'
          description: Approval matrix
      tags:
      - approval
      x-openapi-router-controller: web.src.SAP.generated.controllers.approval_controller
  /approvals/{approval_id}/{sequences}:
    delete:
      description: Cancel a pending approval
      operationId: cancel_approval
      parameters:
      - description: Id of approval to cancel
        explode: true
        in: path
        name: approval_id
        required: true
        schema:
          type: string
        style: simple
      - description: semicolon sperated sequence ids to rejoke approval
        explode: true
        in: path
        name: sequences
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          description: Approval cancelled successfully.
      tags:
      - approval
      x-openapi-router-controller: web.src.SAP.generated.controllers.approval_controller
  /gdpr/extract:
    get:
      description: Extract all data given a personal identifier
      operationId: extract_data_from_pi
      parameters:
      - description: Identifier type
        explode: true
        in: query
        name: identifier_type
        required: true
        schema:
          $ref: '#/components/schemas/PersonalIdentifierType'
        style: form
      - description: Personal identifier number.
        explode: true
        in: query
        name: identifier
        required: true
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PersonalData'
          description: OK
      tags:
      - gdpr
      x-openapi-router-controller: web.src.SAP.generated.controllers.gdpr_controller
  /gdpr/forget:
    get:
      description: Forget about a person identifer, GDPR right to be forgotten
      operationId: forget_pii
      parameters:
      - description: Identifier type
        explode: true
        in: query
        name: identifier_type
        required: true
        schema:
          $ref: '#/components/schemas/PersonalIdentifierType'
        style: form
      - description: Personal identifier number.
        explode: true
        in: query
        name: identifier
        required: true
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PersonalData'
          description: OK
      tags:
      - gdpr
      x-openapi-router-controller: web.src.SAP.generated.controllers.gdpr_controller
  /health_ext_lims:
    get:
      operationId: health_ext_lims
      parameters: []
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
          description: OK
      tags:
      - health
      x-openapi-router-controller: web.src.SAP.generated.controllers.health_controller
      x-codegen-request-body-name: query
  /health_ext_tbr:
    get:
      operationId: health_ext_tbr
      parameters: []
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
          description: OK
      tags:
      - health
      x-openapi-router-controller: web.src.SAP.generated.controllers.health_controller
      x-codegen-request-body-name: query
  /me:
    get:
      description: Describe the current user and their permissions
      operationId: who_am_i
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInfo'
          description: User info
      tags:
      - user
      x-openapi-router-controller: web.src.SAP.generated.controllers.user_controller
  /microreact_integration:
    post:
      description: Send to Microreact
      operationId: send_to_microreact
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewMicroreactProjectRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewMicroreactProjectResponse'
          description: Microreact Response
      tags:
      - microreact
      x-openapi-router-controller: web.src.SAP.generated.controllers.microreact_controller
      x-codegen-request-body-name: body
  /microreact_integration/base_url:
    get:
      description: Get the base url to Microreact
      operationId: get_microreact_url
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MicroreactUrlResponse'
          description: Microreact Response
      tags:
      - microreact
      x-openapi-router-controller: web.src.SAP.generated.controllers.microreact_controller
  /nearest_neighbors:
    post:
      description: Nearest Neighbors
      operationId: post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NearestNeighborsRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NearestNeighborsResponse'
          description: Nearest Neighbors Response
      tags:
      - nearest_neighbors
      x-openapi-router-controller: web.src.SAP.generated.controllers.nearest_neighbors_controller
      x-codegen-request-body-name: body
  /samples/add_to_cluster:
    post:
      operationId: add_to_cluster
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddToCluster'
      responses:
        "204":
          description: Samples added to cluster.
      tags:
      - samples
      x-openapi-router-controller: web.src.SAP.generated.controllers.samples_controller
  /samples/{sample_id}:
    get:
      description: Get an individual sample by id
      operationId: get_sample_by_id
      parameters:
      - description: id of sample
        explode: false
        in: path
        name: sample_id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Sample'
          description: Sample
      tags:
      - samples
      x-openapi-router-controller: web.src.SAP.generated.controllers.samples_controller
  /upload/bulk_metadata:
    post:
      description: Manually upload metadata for previously uploaded sequence files
      operationId: bulk_metadata
      requestBody:
        content:
          multipart/form-data:
            encoding:
              path:
                contentType: text/plain
                style: form
              metadata_tsv:
                contentType: text/tsv
                style: form
            schema:
              $ref: '#/components/schemas/BulkUploadRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UploadResponse'
          description: Isolate uploaded successfully.
        "299":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UploadResponse'
          description: Isolate upload failed. Reports errors.
      tags:
      - upload
      x-openapi-router-controller: web.src.SAP.generated.controllers.upload_controller
      x-codegen-request-body-name: query
  /upload/multi:
    post:
      description: Manually upload multiple sequences with metadata
      operationId: multi_upload
      requestBody:
        content:
          multipart/form-data:
            encoding:
              metadata_tsv:
                contentType: text/tsv
                style: form
              files:
                contentType: application/gzip
                style: form
            schema:
              $ref: '#/components/schemas/MultiUploadRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UploadResponse'
          description: Isolate uploaded successfully.
        "299":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UploadResponse'
          description: Isolate upload failed. Reports errors.
      tags:
      - upload
      x-openapi-router-controller: web.src.SAP.generated.controllers.upload_controller
      x-codegen-request-body-name: query
  /upload/single_upload:
    post:
      description: Manually upload isolate with metadata
      operationId: single_upload
      requestBody:
        content:
          multipart/form-data:
            encoding:
              metadata:
                contentType: application/json
                style: form
              files:
                contentType: application/gzip
                style: form
            schema:
              $ref: '#/components/schemas/SingleUploadRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UploadResponse'
          description: Isolate uploaded successfully.
        "299":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UploadResponse'
          description: Isolate upload failed. Reports errors.
      tags:
      - upload
      x-openapi-router-controller: web.src.SAP.generated.controllers.upload_controller
      x-codegen-request-body-name: query
  /user/views:
    get:
      operationId: get_user_views
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/UserDefinedView'
                type: array
          description: Return user-defined view collection for the authenticated user
      tags:
      - user
      x-openapi-router-controller: web.src.SAP.generated.controllers.user_controller
    post:
      operationId: create_user_view
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDefinedView'
      responses:
        "204":
          description: User-defined view created.
      tags:
      - user
      x-openapi-router-controller: web.src.SAP.generated.controllers.user_controller
  /user/views/{name}:
    delete:
      description: Delete an existing view
      operationId: delete_view
      parameters:
      - description: Name of view to delete
        explode: false
        in: path
        name: name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          description: View deleted successfully.
      tags:
      - user
      x-openapi-router-controller: web.src.SAP.generated.controllers.user_controller
  /workspace/clone:
    post:
      operationId: clone_workspace
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CloneWorkspace'
      responses:
        "204":
          description: Workspace cloned.
      tags:
      - workspaces
      x-openapi-router-controller: web.src.SAP.generated.controllers.workspaces_controller
  /workspace/{workspace_id}/{sample_id}:
    delete:
      description: Delete sample from workspace
      operationId: delete_workspace_sample
      parameters:
      - description: Id of workspace to modify
        explode: false
        in: path
        name: workspace_id
        required: true
        schema:
          type: string
        style: simple
      - description: Id of the sample to remove
        explode: false
        in: path
        name: sample_id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          description: Sample removed from workspace successfully.
      tags:
      - workspaces
      x-openapi-router-controller: web.src.SAP.generated.controllers.workspaces_controller
  /workspaces:
    get:
      description: Gets workspaces
      operationId: get_workspaces
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Workspace'
                type: array
          description: Workspaces info
      tags:
      - workspaces
      x-openapi-router-controller: web.src.SAP.generated.controllers.workspaces_controller
    post:
      operationId: create_workspace
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateWorkspace'
      responses:
        "204":
          description: Workspace created.
      tags:
      - workspaces
      x-openapi-router-controller: web.src.SAP.generated.controllers.workspaces_controller
  /workspaces/create_from_sequence_ids:
    post:
      operationId: create_workspace_from_sequence_ids
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateWorkspace'
      responses:
        "204":
          description: Workspace created.
      tags:
      - workspaces
      x-openapi-router-controller: web.src.SAP.generated.controllers.workspaces_controller
  /workspaces/{workspace_id}:
    delete:
      description: Delete an existing workspace
      operationId: delete_workspace
      parameters:
      - description: Id of workspace to delete
        explode: false
        in: path
        name: workspace_id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          description: Workspace deleted successfully.
      tags:
      - workspaces
      x-openapi-router-controller: web.src.SAP.generated.controllers.workspaces_controller
    get:
      description: Get an existing workspace
      operationId: get_workspace
      parameters:
      - description: Id of workspace to get
        explode: false
        in: path
        name: workspace_id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkspaceInfo'
          description: Workspace
      tags:
      - workspaces
      x-openapi-router-controller: web.src.SAP.generated.controllers.workspaces_controller
    post:
      description: Updates an existing workspace
      operationId: post_workspace
      parameters:
      - description: Id of workspace to update
        explode: false
        in: path
        name: workspace_id
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateWorkspace'
      responses:
        "204":
          description: Workspace updated successfully.
      tags:
      - workspaces
      x-openapi-router-controller: web.src.SAP.generated.controllers.workspaces_controller
  /workspaces/{workspace_id}/data:
    get:
      description: Get an workspace data
      operationId: get_workspace_data
      parameters:
      - description: Id of workspace to get
        explode: false
        in: path
        name: workspace_id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  items: {}
                  type: array
                type: array
          description: Data
      security:
      - microreactjwt: []
      tags:
      - workspaces
      x-openapi-router-controller: web.src.SAP.generated.controllers.workspaces_controller
components:
  schemas:
    Organization:
      enum:
      - SSI
      - FVST
      - Other
      type: string
    TreeMethod:
      enum:
      - single
      - complete
      - average
      - weighted
      - centroid
      - median
      - ward
      type: string
    AnalysisHistory:
      example:
        items:
        - null
        - null
      properties:
        items:
          items:
            $ref: '#/components/schemas/AnalysisResult'
          type: array
      type: object
    SingleAnalysisResult:
      $ref: '#/components/schemas/AnalysisResult'
    PageOfAnalysis:
      example:
        paging_token: paging_token
        approval_matrix:
          key:
            key: approval_matrix
        total_count: 0
        items:
        - null
        - null
      properties:
        paging_token:
          nullable: true
          type: string
        total_count:
          type: integer
        items:
          items:
            $ref: '#/components/schemas/AnalysisResult'
          type: array
        approval_matrix:
          additionalProperties:
            additionalProperties:
              $ref: '#/components/schemas/ApprovalStatus'
            type: object
          type: object
      required:
      - approval_matrix
      - items
      - paging_token
      - total_count
    QueryOperator:
      enum:
      - AND
      - OR
      - AND NOT
      - OR NOT
      - <implicit>
      type: string
    QueryRangeInclusivity:
      enum:
      - left
      - right
      - both
      - none
      type: string
    QueryOperand:
      example:
        term_max: term_max
        field: field
        left: '{}'
        prefix: prefix
        term: term
        right: '{}'
        term_min: term_min
      properties:
        operator:
          $ref: '#/components/schemas/QueryOperator'
        left:
          type: object
        right:
          type: object
        field:
          type: string
        term:
          nullable: true
          type: string
        inclusive:
          $ref: '#/components/schemas/QueryRangeInclusivity'
        term_min:
          nullable: true
          type: string
        term_max:
          nullable: true
          type: string
        prefix:
          nullable: true
          type: string
      type: object
    QueryExpression:
      example:
        left:
          term_max: term_max
          field: field
          left: '{}'
          prefix: prefix
          term: term
          right: '{}'
          term_min: term_min
        right:
          term_max: term_max
          field: field
          left: '{}'
          prefix: prefix
          term: term
          right: '{}'
          term_min: term_min
      properties:
        left:
          $ref: '#/components/schemas/QueryOperand'
        operator:
          $ref: '#/components/schemas/QueryOperator'
        right:
          $ref: '#/components/schemas/QueryOperand'
      type: object
    AnalysisQuery:
      example:
        paging_token: paging_token
        expression:
          left:
            term_max: term_max
            field: field
            left: '{}'
            prefix: prefix
            term: term
            right: '{}'
            term_min: term_min
          right:
            term_max: term_max
            field: field
            left: '{}'
            prefix: prefix
            term: term
            right: '{}'
            term_min: term_min
        filters: '{}'
        page_size: 0
      properties:
        paging_token:
          description: opaque token to supply to get the next page of isolates
          format: byte
          nullable: true
          type: string
        page_size:
          default: 100
          nullable: true
          type: integer
        expression:
          $ref: '#/components/schemas/QueryExpression'
        filters:
          type: object
    HealthResponse:
      example:
        exception:
          helpLink: helpLink
          data: '{}'
          targetSite: targetSite
          source: source
          stackTrace: stackTrace
          message: message
        data: '{}'
        description: description
      properties:
        data:
          type: object
        description:
          type: string
        exception:
          $ref: '#/components/schemas/Exception'
        status:
          $ref: '#/components/schemas/HealthStatus'
      required:
      - description
      - status
      type: object
    Exception:
      example:
        helpLink: helpLink
        data: '{}'
        targetSite: targetSite
        source: source
        stackTrace: stackTrace
        message: message
      properties:
        source:
          type: string
        message:
          type: string
        stackTrace:
          type: string
        data:
          type: object
        targetSite:
          type: string
        helpLink:
          type: string
        innerException:
          $ref: '#/components/schemas/Exception'
      required:
      - message
      type: object
    HealthStatus:
      enum:
      - Unhealthy
      - Degraded
      - Healthy
      type: string
    Sample:
      example:
        name: name
        categories:
          resistance:
            summary: summary
            report:
              phenotypes:
                key:
                  genes:
                    key:
                      alignment_length: 1.4658129805029452
                      phenotypes:
                      - phenotypes
                      - phenotypes
                      depth: 5.962133916683182
                      notes:
                      - notes
                      - notes
                      identity: 0.8008281904610115
                      pmids:
                      - pmids
                      - pmids
                      contig_end_pos: 2.3021358869347655
                      contig_start_pos: 5.637376656633329
                      ref_acc: ref_acc
                      gene_id: gene_id
                      ref_seq_length: 6.027456183070403
                      contig: contig
                  grade: 7.061401241503109
                  amr_classes:
                  - amr_classes
                  - amr_classes
      properties:
        name:
          type: string
        categories:
          $ref: '#/components/schemas/Sample_categories'
      type: object
    Phenotype:
      example:
        genes:
          key:
            alignment_length: 1.4658129805029452
            phenotypes:
            - phenotypes
            - phenotypes
            depth: 5.962133916683182
            notes:
            - notes
            - notes
            identity: 0.8008281904610115
            pmids:
            - pmids
            - pmids
            contig_end_pos: 2.3021358869347655
            contig_start_pos: 5.637376656633329
            ref_acc: ref_acc
            gene_id: gene_id
            ref_seq_length: 6.027456183070403
            contig: contig
        grade: 7.061401241503109
        amr_classes:
        - amr_classes
        - amr_classes
      properties:
        amr_classes:
          items:
            type: string
          type: array
        genes:
          additionalProperties:
            $ref: '#/components/schemas/Gene'
          type: object
        grade:
          type: number
      type: object
    Gene:
      example:
        alignment_length: 1.4658129805029452
        phenotypes:
        - phenotypes
        - phenotypes
        depth: 5.962133916683182
        notes:
        - notes
        - notes
        identity: 0.8008281904610115
        pmids:
        - pmids
        - pmids
        contig_end_pos: 2.3021358869347655
        contig_start_pos: 5.637376656633329
        ref_acc: ref_acc
        gene_id: gene_id
        ref_seq_length: 6.027456183070403
        contig: contig
      properties:
        gene_id:
          type: string
        identity:
          type: number
        ref_seq_length:
          type: number
        alignment_length:
          type: number
        phenotypes:
          items:
            type: string
          nullable: true
          type: array
        depth:
          type: number
        contig:
          type: string
        contig_start_pos:
          type: number
        contig_end_pos:
          type: number
        notes:
          items:
            type: string
          nullable: true
          type: array
        pmids:
          items:
            type: string
          nullable: true
          type: array
        ref_acc:
          type: string
      type: object
    Column:
      example:
        pii: true
        approves_with:
        - approves_with
        - approves_with
        computed: true
        approvable: true
        editable: true
        editable_format: editable_format
        organizations:
        - null
        - null
        cross_org_editable: true
        gdpr: true
        field_name: field_name
      properties:
        approvable:
          description: True if the column can be approved
          type: boolean
        editable:
          description: True if the column can be edited
          type: boolean
        editable_format:
          description: Format for editable fields. Not required.
          nullable: true
          type: string
        pii:
          description: True if the column should be restricted to viewing only by
            the institution that owns it
          type: boolean
        gdpr:
          description: True if the column should be treated as a 'gdpr' column, subject
            to more strict auditing/logging
          type: boolean
        computed:
          description: |
            True if the column is programmatically calculated by SOFI. Such columns can be approvable in the sense of being transferred to a metadata service as part of an approval, but should not be thought of as 'selectable' or capable of any user-side manipulation.
          type: boolean
        organizations:
          description: List of organizations/institutions who 'own' or should have
            unrestricted access to this field
          items:
            $ref: '#/components/schemas/Organization'
          type: array
        field_name:
          type: string
        approves_with:
          description: List of other columns, if any, that should be sent along when
            this column gets approved
          items:
            type: string
          type: array
        cross_org_editable:
          description: True if the column can be edited by users from other organizations
          type: boolean
    UserDefinedView:
      example:
        column_resizing:
          column_width: 0
          column_widths:
            key: '{}'
        hidden_columns:
        - hidden_columns
        - hidden_columns
        name: name
        sort_by:
        - id: id
          desc: true
        - id: id
          desc: true
        column_order:
        - column_order
        - column_order
      properties:
        name:
          type: string
        hidden_columns:
          items:
            type: string
          type: array
        column_resizing:
          $ref: '#/components/schemas/UserDefinedView_column_resizing'
        sort_by:
          items:
            $ref: '#/components/schemas/UserDefinedView_sort_by'
          type: array
        column_order:
          items:
            type: string
          type: array
      type: object
    ApprovalRequest:
      example:
        required_values:
          key:
            key: required_values
        matrix:
          key:
            key: matrix
      properties:
        matrix:
          additionalProperties:
            additionalProperties:
              $ref: '#/components/schemas/ApprovalStatus'
            type: object
          type: object
        required_values:
          additionalProperties:
            additionalProperties:
              type: string
            type: object
          type: object
      required:
      - matrix
      type: object
    Approval:
      allOf:
      - $ref: '#/components/schemas/ApprovalRequest'
      - $ref: '#/components/schemas/Approval_allOf'
    ApprovalStatus:
      enum:
      - pending
      - rejected
      - approved
      type: string
    ApprovalMatrix:
      additionalProperties:
        additionalProperties:
          $ref: '#/components/schemas/ApprovalStatus'
        type: object
      type: object
    AnalysisChange:
      additionalProperties:
        additionalProperties:
          type: string
        type: object
      type: object
    MetadataReloadRequest:
      example:
        isolateId: isolateId
      properties:
        isolateId:
          type: string
        institution:
          $ref: '#/components/schemas/Organization'
      required:
      - institution
      - isolateId
      type: object
    MetadataReloadResponse:
      discriminator:
        propertyName: institution
      oneOf:
      - $ref: '#/components/schemas/TbrMetadata'
      - $ref: '#/components/schemas/LimsMetadata'
    Resistance:
      enum:
      - Sensitiv
      - Resistent
      type: string
    BaseMetadata:
      properties:
        id:
          type: string
        sequence_id:
          type: string
        sequence_filename:
          type: string
        isolate_id:
          type: string
        institution:
          $ref: '#/components/schemas/Organization'
        project_number:
          type: string
        project_title:
          type: string
        date_sample:
          format: date-time
          type: string
        date_received:
          format: date-time
          type: string
        date_sofi:
          format: date-time
          type: string
        run_id:
          type: string
        public_number:
          type: string
        primary_isolate:
          type: boolean
      required:
      - date_received
      - id
      - institution
      - isolate_id
      - primary_isolate
      - run_id
      - sequence_id
    TbrSpecificMetadata:
      properties:
        cpr_nr:
          type: string
        gender:
          enum:
          - M
          - K
          type: string
        name:
          type: string
          x-faker: name.findName
        age:
          maximum: 128
          minimum: 0
          type: integer
        travel:
          type: string
        travel_country:
          type: string
          x-faker: address.country
        date_run:
          format: date-time
          type: string
        date_received_kma:
          format: date-time
          type: string
        kma:
          type: string
        region:
          type: string
        fud_number:
          type: string
        cluster_id:
          type: string
        date_epi:
          type: string
      required:
      - run_date
      type: object
    TbrMetadata:
      allOf:
      - $ref: '#/components/schemas/BaseMetadata'
      - $ref: '#/components/schemas/TbrSpecificMetadata'
    LimsSpecificMetadata:
      properties:
        chr_number:
          type: string
        cvr_number:
          type: string
        aut_number:
          type: string
        product_type:
          type: string
        product:
          type: string
        origin_country:
          type: string
          x-faker: address.country
        animal_species:
          type: string
        sample_info:
          type: string
      type: object
    LimsMetadata:
      allOf:
      - $ref: '#/components/schemas/BaseMetadata'
      - $ref: '#/components/schemas/LimsSpecificMetadata'
    AnalysisResult:
      allOf:
      - $ref: '#/components/schemas/BaseMetadata'
      - $ref: '#/components/schemas/LimsSpecificMetadata'
      - $ref: '#/components/schemas/TbrSpecificMetadata'
      - $ref: '#/components/schemas/AnalysisResult_allOf'
    NewickTreeResponse:
      example:
        tree: tree
      properties:
        tree:
          type: string
      required:
      - tree
      type: object
    UploadMetadataFields:
      description: Corresponds to fields of the metadata.tsv file for initiating an
        execution of the analysis tool pipeline
      properties:
        sample_id:
          type: string
        provided_species:
          type: string
        group:
          type: string
        experiment_name:
          type: string
        sequence_run_date:
          format: date-time
          type: string
        sofi_sequence_id:
          type: string
        project_no:
          type: string
        project_title:
          type: string
      type: object
    SingleUploadRequest:
      properties:
        metadata:
          format: binary
          type: string
        files:
          items:
            format: binary
            type: string
          type: array
      type: object
    MultiUploadRequest:
      properties:
        metadata_tsv:
          format: binary
          type: string
        files:
          items:
            format: binary
            type: string
          type: array
      required:
      - files
      - metadata_tsv
      type: object
    BulkUploadRequest:
      properties:
        path:
          type: string
        metadata_tsv:
          format: binary
          type: string
      required:
      - metadata_tsv
      - path
      type: object
    UploadResponse:
      example:
        errors:
        - errors
        - errors
      properties:
        errors:
          items:
            type: string
          type: array
      type: object
    PersonalIdentifierType:
      enum:
      - CPR
      - CVR
      - CHR
      type: string
    PersonalData:
      example:
        data: data
      properties:
        data:
          type: string
      required:
      - data
      type: object
    DataClearance:
      enum:
      - own-institution
      - cross-institution
      - all
      type: string
    Permission:
      enum:
      - search
      - export
      - approve
      - phylogeny.read
      - phylogeny.write
      - gdpr.manage
      - permissions.write
      type: string
    UserInfo:
      example:
        permissions:
        - null
        - null
        groups:
        - groups
        - groups
        userId: userId
      properties:
        userId:
          type: string
        data_clearance:
          $ref: '#/components/schemas/DataClearance'
        institution:
          $ref: '#/components/schemas/Organization'
        groups:
          items:
            type: string
          type: array
        permissions:
          items:
            $ref: '#/components/schemas/Permission'
          type: array
      type: object
    NearestNeighborsRequest:
      description: Parameters for a REST request for a nearest neighbors calculation.
      example:
        unknownsAreDiffs: true
        id: id
        cutoff: 0
      properties:
        id:
          title: Input Mongo Id
          type: string
        cutoff:
          title: Cutoff
          type: integer
        unknownsAreDiffs:
          title: Unknowns Are Diffs
          type: boolean
      required:
      - cutoff
      - id
      - unknownsAreDiffs
      title: NearestNeighborsRequest
      type: object
    NearestNeighborsResponse:
      example:
        result:
        - null
        - null
        jobId: jobId
        createdAt: createdAt
      properties:
        jobId:
          title: Job Id
          type: string
        createdAt:
          title: Created At
          type: string
        status:
          $ref: '#/components/schemas/BioApiStatus'
        result:
          items:
            $ref: '#/components/schemas/AnalysisResult'
          nullable: true
          title: Result
          type: array
    BioApiStatus:
      enum:
      - init
      - completed
      - error
      title: Status
      type: string
    Workspace:
      example:
        name: name
        id: id
        samples:
        - samples
        - samples
      properties:
        id:
          title: Id
          type: string
        name:
          title: Name
          type: string
        samples:
          items:
            type: string
          title: Samples
          type: array
      required:
      - id
      - name
      type: object
    MicroreactProject:
      example:
        id: id
        url: url
      properties:
        id:
          title: Id
          type: string
        url:
          title: Url
          type: string
      type: object
    CreateWorkspace:
      example:
        name: name
        samples:
        - samples
        - samples
      properties:
        name:
          title: Name
          type: string
        samples:
          items:
            type: string
          title: Samples
          type: array
      required:
      - name
      type: object
    AddToCluster:
      example:
        clusterid: clusterid
        samples:
        - samples
        - samples
      properties:
        clusterid:
          title: ClusterId
          type: string
        samples:
          items:
            type: string
          title: Samples
          type: array
      required:
      - clusterid
      type: object
    CloneWorkspace:
      example:
        name: name
        id: id
      properties:
        name:
          title: Name
          type: string
        id:
          title: Id
          type: string
      required:
      - id
      - name
      type: object
    UpdateWorkspace:
      example:
        samples:
        - samples
        - samples
      properties:
        samples:
          items:
            type: string
          title: Samples
          type: array
      required:
      - samples
      type: object
    WorkspaceInfo:
      example:
        name: name
        microreact:
          id: id
          url: url
        id: id
        samples:
        - null
        - null
      properties:
        id:
          title: Id
          type: string
        name:
          title: Name
          type: string
        samples:
          items:
            $ref: '#/components/schemas/AnalysisResult'
          title: Samples
          type: array
        microreact:
          $ref: '#/components/schemas/MicroreactProject'
      required:
      - name
      - samples
      type: object
    NewMicroreactProjectRequest:
      example:
        workspace: workspace
        tree_methods:
        - null
        - null
        mr_access_token: mr_access_token
      properties:
        workspace:
          type: string
        mr_access_token:
          type: string
        tree_methods:
          items:
            $ref: '#/components/schemas/TreeMethod'
          type: array
      required:
      - mr_access_token
      - tree_methods
      - workspace
      type: object
    NewMicroreactProjectResponse:
      example:
        isOwner: true
        id: id
        url: url
      properties:
        isOwner:
          type: boolean
        id:
          type: string
        url:
          type: string
    MicroreactUrlResponse:
      example:
        url: url
      properties:
        url:
          type: string
    Sample_categories_resistance_report:
      example:
        phenotypes:
          key:
            genes:
              key:
                alignment_length: 1.4658129805029452
                phenotypes:
                - phenotypes
                - phenotypes
                depth: 5.962133916683182
                notes:
                - notes
                - notes
                identity: 0.8008281904610115
                pmids:
                - pmids
                - pmids
                contig_end_pos: 2.3021358869347655
                contig_start_pos: 5.637376656633329
                ref_acc: ref_acc
                gene_id: gene_id
                ref_seq_length: 6.027456183070403
                contig: contig
            grade: 7.061401241503109
            amr_classes:
            - amr_classes
            - amr_classes
      properties:
        phenotypes:
          additionalProperties:
            $ref: '#/components/schemas/Phenotype'
          type: object
      type: object
    Sample_categories_resistance:
      example:
        summary: summary
        report:
          phenotypes:
            key:
              genes:
                key:
                  alignment_length: 1.4658129805029452
                  phenotypes:
                  - phenotypes
                  - phenotypes
                  depth: 5.962133916683182
                  notes:
                  - notes
                  - notes
                  identity: 0.8008281904610115
                  pmids:
                  - pmids
                  - pmids
                  contig_end_pos: 2.3021358869347655
                  contig_start_pos: 5.637376656633329
                  ref_acc: ref_acc
                  gene_id: gene_id
                  ref_seq_length: 6.027456183070403
                  contig: contig
              grade: 7.061401241503109
              amr_classes:
              - amr_classes
              - amr_classes
      properties:
        summary:
          type: string
        report:
          $ref: '#/components/schemas/Sample_categories_resistance_report'
      type: object
    Sample_categories:
      example:
        resistance:
          summary: summary
          report:
            phenotypes:
              key:
                genes:
                  key:
                    alignment_length: 1.4658129805029452
                    phenotypes:
                    - phenotypes
                    - phenotypes
                    depth: 5.962133916683182
                    notes:
                    - notes
                    - notes
                    identity: 0.8008281904610115
                    pmids:
                    - pmids
                    - pmids
                    contig_end_pos: 2.3021358869347655
                    contig_start_pos: 5.637376656633329
                    ref_acc: ref_acc
                    gene_id: gene_id
                    ref_seq_length: 6.027456183070403
                    contig: contig
                grade: 7.061401241503109
                amr_classes:
                - amr_classes
                - amr_classes
      properties:
        resistance:
          $ref: '#/components/schemas/Sample_categories_resistance'
      type: object
    UserDefinedView_column_resizing:
      example:
        column_width: 0
        column_widths:
          key: '{}'
      properties:
        column_widths:
          additionalProperties: true
          type: object
        column_width:
          type: integer
      type: object
    UserDefinedView_sort_by:
      example:
        id: id
        desc: true
      properties:
        desc:
          type: boolean
        id:
          type: string
      type: object
    Approval_allOf:
      properties:
        id:
          type: string
        approver:
          type: string
        timestamp:
          format: date-time
          type: string
        sequence_ids:
          items:
            type: string
          type: array
        status:
          enum:
          - pending
          - cancelled
          - submitted
          type: string
      type: object
    AnalysisResult_allOf_qc_failed_tests:
      properties:
        name:
          type: string
        display_name:
          type: string
        reason:
          type: string
      type: object
    AnalysisResult_allOf:
      properties:
        latest_for_isolate:
          description: sequence_id of latest result with this same isolate_id
          type: string
        resfinder_version:
          type: string
        date_received_kma:
          format: date-time
          type: string
        date_analysis_sofi:
          format: date-time
          type: string
        date_approved_serotype:
          format: date-time
          type: string
        date_approved_qc:
          format: date-time
          type: string
        date_approved_amr:
          format: date-time
          type: string
        date_approved_st:
          format: date-time
          type: string
        date_approved_toxin:
          format: date-time
          type: string
        date_approved_cluster:
          format: date-time
          type: string
        date_approved_cdiff:
          format: date-time
          type: string
        qc_provided_species:
          type: string
        qc_genome1x:
          type: number
        qc_genome10x:
          type: number
        qc_gsize_diff1x10:
          type: number
        qc_avg_coverage:
          type: number
        qc_final:
          enum:
          - A
          - B
          - C
          type: string
        qc_action:
          type: string
        qc_num_contigs:
          type: number
        qc_ambiguous_sites:
          type: number
        qc_num_reads:
          type: number
        qc_main_sp_plus_uncl:
          type: number
        qc_unclassified_reads:
          type: number
        qc_db_id:
          type: string
        qc_db_id2:
          type: string
        qc_failed_tests:
          items:
            $ref: '#/components/schemas/AnalysisResult_allOf_qc_failed_tests'
          type: array
        call_percent:
          type: number
        multiple_alleles:
          type: number
        subspecies:
          type: string
        species_final:
          type: string
        st:
          type: string
        st_final:
          type: integer
        st_alleles:
          type: object
        pathotype:
          type: string
        pathotype_final:
          type: string
        sero_enterobase:
          type: string
        sero_seqsero:
          type: string
        sero_antigen_seqsero:
          type: string
        sero_d_tartrate:
          type: string
        sero_serotype_finder:
          type: string
        serotype_final:
          type: string
        adhesion_final:
          type: string
        virulence_genes:
          type: string
        toxins_final:
          type: string
        infection_source:
          type: string
        resistance_genes:
          type: string
        amr_profile:
          type: string
        comment:
          type: string
        comment_cluster:
          type: string
        comment_general:
          type: string
        comment_supplementary:
          type: string
        comment_qc:
          type: string
        amr_ami:
          $ref: '#/components/schemas/Resistance'
        amr_amp:
          $ref: '#/components/schemas/Resistance'
        amr_azi:
          $ref: '#/components/schemas/Resistance'
        amr_fep:
          $ref: '#/components/schemas/Resistance'
        amr_fot:
          $ref: '#/components/schemas/Resistance'
        amr_f_c:
          $ref: '#/components/schemas/Resistance'
        amr_fox:
          $ref: '#/components/schemas/Resistance'
        amr_taz:
          $ref: '#/components/schemas/Resistance'
        amr_t_c:
          $ref: '#/components/schemas/Resistance'
        amr_chl:
          $ref: '#/components/schemas/Resistance'
        amr_cip:
          $ref: '#/components/schemas/Resistance'
        amr_cli:
          $ref: '#/components/schemas/Resistance'
        amr_col:
          $ref: '#/components/schemas/Resistance'
        amr_dap:
          $ref: '#/components/schemas/Resistance'
        amr_etp:
          $ref: '#/components/schemas/Resistance'
        amr_ery:
          $ref: '#/components/schemas/Resistance'
        amr_fus:
          $ref: '#/components/schemas/Resistance'
        amr_gen:
          $ref: '#/components/schemas/Resistance'
        amr_imi:
          $ref: '#/components/schemas/Resistance'
        amr_kan:
          $ref: '#/components/schemas/Resistance'
        amr_lzd:
          $ref: '#/components/schemas/Resistance'
        amr_mero:
          $ref: '#/components/schemas/Resistance'
        amr_mup:
          $ref: '#/components/schemas/Resistance'
        amr_nal:
          $ref: '#/components/schemas/Resistance'
        amr_pen:
          $ref: '#/components/schemas/Resistance'
        amr_syn:
          $ref: '#/components/schemas/Resistance'
        amr_rif:
          $ref: '#/components/schemas/Resistance'
        amr_str:
          $ref: '#/components/schemas/Resistance'
        amr_sul:
          $ref: '#/components/schemas/Resistance'
        amr_tei:
          $ref: '#/components/schemas/Resistance'
        amr_trm:
          $ref: '#/components/schemas/Resistance'
        amr_tet:
          $ref: '#/components/schemas/Resistance'
        amr_tia:
          $ref: '#/components/schemas/Resistance'
        amr_tgc:
          $ref: '#/components/schemas/Resistance'
        amr_tmp:
          $ref: '#/components/schemas/Resistance'
        amr_van:
          $ref: '#/components/schemas/Resistance'
        cgmlst_schema:
          type: object
        trst:
          type: string
        tcda:
          type: string
        tcdb:
          type: string
        cdta_cdtb:
          type: string
        del_117:
          type: string
        a117t:
          type: string
        cdiff_details:
          type: string
        adhaesion:
          type: string
        toxin:
          type: string
        toxin_details:
          type: string
        bifrost_min_read_check:
          type: string
        bifrost_whats_my_species:
          type: string
        bifrost_assemblatron:
          type: string
        bifrost_assembly_qc:
          type: string
        bifrost_ssi_stamper:
          type: string
        bifrost_cge_mlst:
          type: string
        bifrost_cge_resfinder:
          type: string
        bifrost_seqsero:
          type: string
        bifrost_enterobase:
          type: string
        bifrost_salmonella_subspecies_dtartrate:
          type: string
        bifrost_chewbbaca:
          type: string
        bifrost_sp_ecoli:
          type: string
        bifrost_sp_cdiff:
          type: string
        bifrost_amrfinderplus:
          type: string
      required:
      - isolate_id
      type: object
  securitySchemes:
    jwt:
      bearerFormat: JWT
      scheme: bearer
      type: http
      x-bearerInfoFunc: web.src.SAP.generated.controllers.security_controller_.info_from_jwt
    microreactjwt:
      bearerFormat: JWT
      scheme: bearer
      type: http
      x-bearerInfoFunc: web.src.SAP.generated.controllers.security_controller_.info_from_microreactjwt
